### PR TITLE
stathat-encoder: stathat encoder for app metrics

### PR DESCRIPTION
**Pull request by mohit**
tested by sending some random metrics. this is a prototype to start sending some real application metrics to StatHat and make decision if it works for app level alerting. 

Issues:

- one HTTP request per metric which means we might run into scalability issues
- for counters since syslog ignores repeated messages we will have to ensure that some id is logged.

### CODE REVIEW

**Comment by mohit** [comment]
cc: @rgarcia

**Comment by rgarcia** [comment]
Cool! I think there's a way to send batch requests

**Comment by mohit** [comment]
Yes there is - and Daniel has built an aggregator for influx which we can use as a template. However, I'd really like to invest in having a few metrics go through and test the whole flow before investing time into building a scalable output

**Comment by dfuentes** [comment]
lgtm

**Pull request merged**
