### PR TITLE
Signalfxbatch Filter - dimensions blacklist

### PR DESCRIPTION
**Pull request by nathanleiby**
Issue: https://clever.atlassian.net/browse/INFRA-877

Support for fields blacklist instead of the prior `dimensions` field whitelist.

This matches our `influxdbbatch` filter. 
It helps to send rich metadata while configuring few (or even just 1) `signalfxbatch` filter

Also removed signalfx encoder, which is no longer used.

### CODE REVIEW

**Comment by nathanleiby** [comment]
@xavi - hubot assigned you. 
@dfuentes would appreciate a look given your work on the influxdb equivalent.

Thanks!

**Comment by dfuentes** [comment]
Looks good to me

**Comment by xavi-** [comment]
lgtm

**Comment by nathanleiby** [comment]
This will break existing toml, so I'll wait until that update is ready before merging this

**Pull request merged**
