### PR TITLE
remove field_encoder

### PR DESCRIPTION
**Pull request by nathanleiby**
Field encoder is a heavy handed implementation in Go.

lua/filters/fieldfix.lua is more flexible and powerful

### CODE REVIEW

**Comment by bstein-clever** [comment]
I love commits that remove dead code! LGTM, pending the other one. :)

**Comment by nikhilpandit** [comment]
For future: We should build a `heka-private` container pointing to the latest `heka-clever-plugin` commit if the commit removes or modifies Go code. This will ensure that the removal / modification doesn't break the tests on `heke-private`.

cc @mohit

**Comment by nathanleiby** [comment]
@nikhilpandit makes sense! I think we can consolidate our heka setup substantially to make it easier to digest https://clever.atlassian.net/browse/INFRA-612

**Comment by nikhilpandit** [comment]
:+1:

There also seem to be issues with tests in this repo. Looking at it again, the tests should have caught the issue on this repo too.

**Pull request merged**
